api_platform:
    title: 'BILEMO API'
  
    description: 'API REST pour la société BileMo, une entreprise fictive de vente de téléphone portable'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        order: 'DESC'
        pagination:
            enabled: false
            client_enabled: true
            client_items_per_page: true
    
    #http_cache:
    #    invalidation:
    #        enabled: true
    #        varnish_urls: ['%env(VARNISH_URL)%']
    #    public: true
    #defaults:
    #    cache_headers:
    #        max_age: 0
    #        shared_max_age: 600
    #        vary: ['Content-Type', 'Authorization', 'Origin']